name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - uses: actions/checkout@v4

      # Node.js セットアップ
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      # 依存関係インストール
      - run: npm ci

      # テスト実行 & カバレッジ生成
      - run: npx vitest run --coverage

      # Codecov にレポートをアップロード
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
